from gramps.version import major_version

register(GRAMPLET,
         id = "Dates",
         name = _("Dates"),
         description = _("Event Gramplet for reformatting invalid Dates"),
         authors = ["Kari Kujansuu"],
         authors_email = ["kari.kujansuu@gmail.com"],  
         status = STABLE,
         audience = EVERYONE,
         version = '1.1.4',
         gramps_target_version = major_version,
         fname = "Dates.py",
         gramplet = 'Dates',
         height = 375,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet_title = _("Dates"),
         help_url="Addon:Isotammi_addons#Dates",
         include_in_listing = True,
         navtypes=["Event"],
        )
