from gramps.version import major_version

register(GRAMPLET,
         id="Multimergegramplet Gramplet",
         name=_("Multimerge Gramplet"),
         description = _("Multimerge Gramplet allows the merging of multiple objects in a single step"),
         status=STABLE, 
         audience = EVERYONE,
         fname="multimergegramplet.py",
         authors = ['Kari Kujansuu', 'Nick Hall'],
         authors_email = ['kari.kujansuu@gmail.com', 'nick-h@gramps-project.org'],
         height=230,
         expand=True,
         gramplet = 'MultiMergeGramplet',
         gramplet_title=_("MultiMergeGramplet"),
         detached_width = 510,
         detached_height = 480,
         version = '1.1.8',
         gramps_target_version = major_version,
         help_url="Addon:Isotammi_addons#Multimerge_Gramplet",
         navtypes=["Person","Family","Place","Source","Repository","Note","Event",
                   "Citation","Media"],
         )
