from gramps.version import major_version

register(GRAMPLET,
         id = "PlaceTool",
         name = _("PlaceTool"),
         description = _("Gramplet to harmonize multiple places"),
         authors = ["Kari Kujansuu"],
         authors_email = ["kari.kujansuu@gmail.com"],
         status = STABLE,
         audience = EVERYONE,
         version = '1.1.4',
         gramps_target_version = major_version,
         fname = "PlaceTool.py",
         gramplet = 'PlaceTool',
         height = 375,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet_title = _("PlaceTool"),
         help_url="Addon:Isotammi_addons#Place_tool",
         include_in_listing = True,
         navtypes=["Place"],
        )
