from gramps.version import major_version

register(GRAMPLET,
         id = "PropertyEditor",
         name = _("PropertyEditor"),
         description = _("Gramplet to simultaneously edit attributes of multiple objects"),
         authors = ["Kari Kujansuu"],
         authors_email = ["kari.kujansuu@gmail.com"],
         status = STABLE,
         audience = EVERYONE,
         version = '1.1.1',
         gramps_target_version = major_version,
         fname = "PropertyEditor.py",
         gramplet = 'PropertyEditor',
         height = 375,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet_title = _("PropertyEditor"),
         help_url="Addon:Isotammi_addons#PropertyEditor",
         include_in_listing = True,
         #navtypes=["Source"],
        )
